$(function(){
    //set template paths
    sap.viz.api.env.Resource.path('sap.viz.api.env.Template.loadPaths',
     ['../../../resources/libs/sap.viz/resources/chart/templates', 
      '../../../resources/libs/sap.viz/resources/geo/templates/?_viz_template_with_css=true'])

    //set map resource path
    sap.viz.api.env.Resource.path("sap.viz.map.Resources", 
      "../../../resources/libs/sap.viz/resources/geo");

    //Apply template
    sap.viz.api.env.Template.set("highcontrast_lumira",function(){
          // initialize a cvom base map
        var baseMapProvider = new sap.viz.geo.basemap.cvom.Provider();

        // create chart
        var map = new sap.viz.geo.Map($('#chart').get(0), {baseMap : baseMapProvider});
        var textArea = document.getElementById('code-content');
        // prepare data
        var data = {
          "metadata" : {
            "fields" : [{
              "id" : "Location",
              "name" : "Location",
              "semanticType" : "Dimension",
              "dataType" : "String"
            }, {
              "id" : "Value",
              "name" : "Value",
              "semanticType" : "Measure"
            }]
          },
          "data" : [
              ['ANC. Rép. Yougoslave de Macédoine'],
              ['Adam Adası'],
              ['Afghanistan'],
              ['Afrique du Sud'],
              ['Airija'],
              ['Alankomaat'],
              ['Albaania'],
              ['Alemanha'],
              ['Algeria'],
              ['Amerikaanse Maagdeneilanden'],
              ['Amerikas Förenta Stater'],
              ['An Bhealarúis'],
              ['An Bheilg'],
              ['An Bhoisnia Heirseagaivéin'],
              ['An Bhulgáir'],
              ['An Chróit'],
              ['An Danmhairg'],
              ['An Eastóin'],
              ['An Eilvéis'],
              ['An Fhionlainn'],
              ['An Ghréig'],
              ['An Iodáil'],
              ['An Iorua'],
              ['An Laitvia'],
              ['An Liotuáin'],
              ['An Mholdóiv'],
              ['An Ostair'],
              ['An Pholainn'],
              ['An Phortaingéil'],
              ['An Rómáin'],
              ['An Rúis'],
              ['An Spáinn'],
              ['An Tseirbia'],
              ['An Tslóivéin'],
              ['An Tslóvaic'],
              ['An Tsualainn'],
              ['An Tuirc'],
              ['An Ungáir'],
              ['An Íoslainn'],
              ['An Úcráin'],
              ['Andora'],
              ['Angola'],
              ['Arabia Saudita'],
              ['Argentina'],
              ['Armenia'],
              ['Australia'],
              ['Azerbaijan'],
              ['Bahamas, The'],
              ['Bahrain'],
              ['Banco Oeste'],
              ['Bangladesh'],
              ['Barbade'],
              ['Belize'],
              ['Benin'],
              ['Bhutan'],
              ['Bolivia'],
              ['Botsuana'],
              ['Brasil'],
              ['Brunei Darussalam'],
              ['Burkina Faso'],
              ['Burma (Myanmar)'],
              ['Burundi'],
              ['Cambodia'],
              ['Cameroon'],
              ['Canada'],
              ['Cape Verde'],
              ['Cayman Islands'],
              ['Central African Republic'],
              ['Chad'],
              ['Chile'],
              ['China'],
              ['Colombia'],
              ['Congo, Democratic Republic'],
              ['Congo, Republic of the'],
              ['Costa Rica'],
              ['Cote D Ivoire (Ivory Coast)'],
              ['Crna Gora'],
              ['Csehország'],
              ['Cuba'],
              ['Cyprus un Neutral Zone'],
              ['Cyprus'],
              ['Djibouti'],
              ['Dominicaanse Republiek'],
              ['East Timor'],
              ['Ecuador'],
              ['Egipto'],
              ['El Salvador'],
              ['Emirati Arabi Uniti'],
              ['Equatorial Guinea'],
              ['Eritrea'],
              ['Ethiopia'],
              ['Falkland Islands (Islas Malvinas)'],
              ['Ffrainc'],
              ['Fiji'],
              ['Frans-Guadeloupe'],
              ['Frans-Guyana'],
              ['Frans-Martinique'],
              ['Frans-Reunion'],
              ['Gabon'],
              ['Gambia'],
              ['Gaza Strip'],
              ['Georgia'],
              ['Ghana'],
              ['Giamaica'],
              ['Giordania'],
              ['Greenland'],
              ['Guatemala'],
              ['Guinea'],
              ['Guinea-Bissau'],
              ['Guyana'],
              ['Haiti'],
              ['Honduras'],
              ['India'],
              ['Irak'],
              ['Iran'],
              ['Israel'],
              ['Japan'],
              ['Jemen'],
              ['Kasachstan'],
              ['Katar'],
              ['Kenia'],
              ['Kirghizistan'],
              ['Koeweit'],
              ['North Kore'],
              ['Laos'],
              ['Lebanon'],
              ['Lesotho'],
              ['Liberia'],
              ['Libia'],
              ['Lichtensztajn'],
              ['Liuksemburgas'],
              ['Madagascar'],
              ['Malaisie'],
              ['Malawi'],
              ['Mali'],
              ['Malta'],
              ['Mauritania'],
              ['Mauritius'],
              ['Mayotte'],
              ['Messico'],
              ['Mongolei'],
              ['Morocco'],
              ['Mosambik'],
              ['Namibia'],
              ['Nepal'],
              ['New Caledonia'],
              ['Nicaragua'],
              ['Niger'],
              ['Nigeria'],
              ['Nouvelle-Zélande'],
              ['Oezbekistan'],
              ['Oman'],
              ['PR'],
              ['Pakistan'],
              ['Panama'],
              ['Papua New Guinea'],
              ['Paraguay'],
              ['Peru'],
              ['Philippines'],
              ['Renju Unit'],
              ['República Bolivariana de Venezuela'],
              ['Rwanda'],
              ['Saint Lucia'],
              ['Saint Pierre and Miquelon'],
              ['Senegal'],
              ['Sierra Leone'],
              ['Singapore'],
              ['Siria'],
              ['Soedan'],
              ['Solomon Islands'],
              ['Somalia'],
              ['South Korea'],
              ['Sri Lanka'],
              ['Suriname'],
              ['Svalbard'],
              ['Swasiland'],
              ['Taiwan'],
              ['Tajikistan'],
              ['Tanzania'],
              ['Thailand'],
              ['Togo'],
              ['Trinidad and Tobago'],
              ['Tunisia'],
              ['Turkmenistan'],
              ['Uganda'],
              ['Uruguay'],
              ['Vietnam'],
              ['Zambia'],
              ['Zimbabue'],
              ['Indonesi'],
              ['香港-中國'],
          ],
          "info" : [{
            "type" : "geo",
            "info" : [
                [{'featureId':'23796253,NAVTEQ'}],
                [{'featureId':'20486695,NAVTEQ'}],
                [{'featureId':'23528373,NAVTEQ'}],
                [{'featureId':'23402002,NAVTEQ'}],
                [{'featureId':'20403667,NAVTEQ'}],
                [{'featureId':'23055544,NAVTEQ'}],
                [{'featureId':'20678151,NAVTEQ'}],
                [{'featureId':'20147700,NAVTEQ'}],
                [{'featureId':'22927666,NAVTEQ'}],
                [{'featureId':'21486367,NAVTEQ'}],
                [{'featureId':'21000001,NAVTEQ'}],
                [{'featureId':'22832579,NAVTEQ'}],
                [{'featureId':'20128886,NAVTEQ'}],
                [{'featureId':'20676254,NAVTEQ'}],
                [{'featureId':'20656214,NAVTEQ'}],
                [{'featureId':'20633739,NAVTEQ'}],
                [{'featureId':'20298369,NAVTEQ'}],
                [{'featureId':'20633738,NAVTEQ'}],
                [{'featureId':'20138137,NAVTEQ'}],
                [{'featureId':'20241487,NAVTEQ'}],
                [{'featureId':'20448870,NAVTEQ'}],
                [{'featureId':'20110484,NAVTEQ'}],
                [{'featureId':'20418433,NAVTEQ'}],
                [{'featureId':'20633737,NAVTEQ'}],
                [{'featureId':'20633740,NAVTEQ'}],
                [{'featureId':'20678153,NAVTEQ'}],
                [{'featureId':'20128885,NAVTEQ'}],
                [{'featureId':'20624059,NAVTEQ'}],
                [{'featureId':'20317122,NAVTEQ'}],
                [{'featureId':'20656215,NAVTEQ'}],
                [{'featureId':'20485579,NAVTEQ'}],
                [{'featureId':'20215059,NAVTEQ'}],
                [{'featureId':'23832388,NAVTEQ'}],
                [{'featureId':'20633685,NAVTEQ'}],
                [{'featureId':'20428682,NAVTEQ'}],
                [{'featureId':'20298368,NAVTEQ'}],
                [{'featureId':'22709441,NAVTEQ'}],
                [{'featureId':'20613038,NAVTEQ'}],
                [{'featureId':'23517927,NAVTEQ'}],
                [{'featureId':'23674902,NAVTEQ'}],
                [{'featureId':'20300625,NAVTEQ'}],
                [{'featureId':'22927764,NAVTEQ'}],
                [{'featureId':'21375962,NAVTEQ'}],
                [{'featureId':'23294156,NAVTEQ'}],
                [{'featureId':'22928263,NAVTEQ'}],
                [{'featureId':'21482883,NAVTEQ'}],
                [{'featureId':'22928312,NAVTEQ'}],
                [{'featureId':'23382869,NAVTEQ'}],
                [{'featureId':'21420453,NAVTEQ'}],
                [{'featureId':'23919168,NAVTEQ'}],
                [{'featureId':'22928307,NAVTEQ'}],
                [{'featureId':'22928245,NAVTEQ'}],
                [{'featureId':'23671176,NAVTEQ'}],
                [{'featureId':'22927676,NAVTEQ'}],
                [{'featureId':'22928283,NAVTEQ'}],
                [{'featureId':'22928244,NAVTEQ'}],
                [{'featureId':'22832174,NAVTEQ'}],
                [{'featureId':'23028911,NAVTEQ'}],
                [{'featureId':'23287002,NAVTEQ'}],
                [{'featureId':'22927672,NAVTEQ'}],
                [{'featureId':'22928301,NAVTEQ'}],
                [{'featureId':'22927763,NAVTEQ'}],
                [{'featureId':'22928258,NAVTEQ'}],
                [{'featureId':'22927743,NAVTEQ'}],
                [{'featureId':'21041602,NAVTEQ'}],
                [{'featureId':'22927664,NAVTEQ'}],
                [{'featureId':'23382874,NAVTEQ'}],
                [{'featureId':'22927744,NAVTEQ'}],
                [{'featureId':'22927730,NAVTEQ'}],
                [{'featureId':'23488354,NAVTEQ'}],
                [{'featureId':'22928332,NAVTEQ'}],
                [{'featureId':'23656250,NAVTEQ'}],
                [{'featureId':'22927698,NAVTEQ'}],
                [{'featureId':'22927626,NAVTEQ'}],
                [{'featureId':'23671186,NAVTEQ'}],
                [{'featureId':'22927695,NAVTEQ'}],
                [{'featureId':'22903211,NAVTEQ'}],
                [{'featureId':'20427915,NAVTEQ'}],
                [{'featureId':'23671187,NAVTEQ'}],
                [{'featureId':'23740915,NAVTEQ'}],
                [{'featureId':'23502650,NAVTEQ'}],
                [{'featureId':'22927701,NAVTEQ'}],
                [{'featureId':'23671189,NAVTEQ'}],
                [{'featureId':'23714314,NAVTEQ'}],
                [{'featureId':'22928218,NAVTEQ'}],
                [{'featureId':'23713588,NAVTEQ'}],
                [{'featureId':'23671179,NAVTEQ'}],
                [{'featureId':'21397206,NAVTEQ'}],
                [{'featureId':'22927739,NAVTEQ'}],
                [{'featureId':'22927686,NAVTEQ'}],
                [{'featureId':'22927671,NAVTEQ'}],
                [{'featureId':'22928216,NAVTEQ'}],
                [{'featureId':'20000001,NAVTEQ'}],
                [{'featureId':'23582190,NAVTEQ'}],
                [{'featureId':'23410565,NAVTEQ'}],
                [{'featureId':'23382586,NAVTEQ'}],
                [{'featureId':'23410558,NAVTEQ'}],
                [{'featureId':'23382345,NAVTEQ'}],
                [{'featureId':'22927654,NAVTEQ'}],
                [{'featureId':'22927673,NAVTEQ'}],
                [{'featureId':'23919167,NAVTEQ'}],
                [{'featureId':'22928376,NAVTEQ'}],
                [{'featureId':'22927614,NAVTEQ'}],
                [{'featureId':'23671185,NAVTEQ'}],
                [{'featureId':'23059529,NAVTEQ'}],
                [{'featureId':'23667698,NAVTEQ'}],
                [{'featureId':'23671211,NAVTEQ'}],
                [{'featureId':'22927738,NAVTEQ'}],
                [{'featureId':'22927635,NAVTEQ'}],
                [{'featureId':'23726115,NAVTEQ'}],
                [{'featureId':'23671210,NAVTEQ'}],
                [{'featureId':'23671207,NAVTEQ'}],
                [{'featureId':'22806254,NAVTEQ'}],
                [{'featureId':'23528375,NAVTEQ'}],
                [{'featureId':'23528374,NAVTEQ'}],
                [{'featureId':'23528376,NAVTEQ'}],
                [{'featureId':'22928357,NAVTEQ'}],
                [{'featureId':'22927640,NAVTEQ'}],
                [{'featureId':'22928289,NAVTEQ'}],
                [{'featureId':'21417285,NAVTEQ'}],
                [{'featureId':'23704449,NAVTEQ'}],
                [{'featureId':'22928266,NAVTEQ'}],
                [{'featureId':'21405268,NAVTEQ'}],
                [{'featureId':'22928269,NAVTEQ'}],
                [{'featureId':'22928299,NAVTEQ'}],
                [{'featureId':'23514592,NAVTEQ'}],
                [{'featureId':'22832175,NAVTEQ'}],
                [{'featureId':'22927690,NAVTEQ'}],
                [{'featureId':'22927678,NAVTEQ'}],
                [{'featureId':'20209045,NAVTEQ'}],
                [{'featureId':'20128887,NAVTEQ'}],
                [{'featureId':'22927675,NAVTEQ'}],
                [{'featureId':'23289295,NAVTEQ'}],
                [{'featureId':'22927682,NAVTEQ'}],
                [{'featureId':'22927721,NAVTEQ'}],
                [{'featureId':'23667688,NAVTEQ'}],
                [{'featureId':'22927776,NAVTEQ'}],
                [{'featureId':'22927634,NAVTEQ'}],
                [{'featureId':'22927765,NAVTEQ'}],
                [{'featureId':'22000493,NAVTEQ'}],
                [{'featureId':'22928264,NAVTEQ'}],
                [{'featureId':'23362024,NAVTEQ'}],
                [{'featureId':'23495768,NAVTEQ'}],
                [{'featureId':'22832176,NAVTEQ'}],
                [{'featureId':'22928273,NAVTEQ'}],
                [{'featureId':'23582176,NAVTEQ'}],
                [{'featureId':'23671198,NAVTEQ'}],
                [{'featureId':'23727855,NAVTEQ'}],
                [{'featureId':'23702349,NAVTEQ'}],
                [{'featureId':'23060936,NAVTEQ'}],
                [{'featureId':'22928336,NAVTEQ'}],
                [{'featureId':'21425362,NAVTEQ'}],
                [{'featureId':'21177795,NAVTEQ'}],
                [{'featureId':'22928320,NAVTEQ'}],
                [{'featureId':'23671200,NAVTEQ'}],
                [{'featureId':'23502663,NAVTEQ'}],
                [{'featureId':'22928238,NAVTEQ'}],
                [{'featureId':'23695790,NAVTEQ'}],
                [{'featureId':'23869478,NAVTEQ'}],
                [{'featureId':'UK,NAVTEQ'}],
                [{'featureId':'23355239,NAVTEQ'}],
                [{'featureId':'22927772,NAVTEQ'}],
                [{'featureId':'22928212,NAVTEQ'}],
                [{'featureId':'23715814,NAVTEQ'}],
                [{'featureId':'22927668,NAVTEQ'}],
                [{'featureId':'22927745,NAVTEQ'}],
                [{'featureId':'21160468,NAVTEQ'}],
                [{'featureId':'23528377,NAVTEQ'}],
                [{'featureId':'22927717,NAVTEQ'}],
                [{'featureId':'23502661,NAVTEQ'}],
                [{'featureId':'22927612,NAVTEQ'}],
                [{'featureId':'22928340,NAVTEQ'}],
                [{'featureId':'22928342,NAVTEQ'}],
                [{'featureId':'22928232,NAVTEQ'}],
                [{'featureId':'23667693,NAVTEQ'}],
                [{'featureId':'22832177,NAVTEQ'}],
                [{'featureId':'23525046,NAVTEQ'}],
                [{'featureId':'22928314,NAVTEQ'}],
                [{'featureId':'22927692,NAVTEQ'}],
                [{'featureId':'22888206,NAVTEQ'}],
                [{'featureId':'22927620,NAVTEQ'}],
                [{'featureId':'22928196,NAVTEQ'}],
                [{'featureId':'22927704,NAVTEQ'}],
                [{'featureId':'22928362,NAVTEQ'}],
                [{'featureId':'23835855,NAVTEQ'}],
                [{'featureId':'22928233,NAVTEQ'}],
                [{'featureId':'22928359,NAVTEQ'}],
                [{'featureId':'22927728,NAVTEQ'}],
                [{'featureId':'23930431,NAVTEQ'}],
                [{'featureId':'23457314,NAVTEQ'}],
                [{'featureId':'21162124,NAVTEQ'}],
            ]
          }]
        };

        var ds = new sap.viz.api.data.FlatTableDataset(data);

        // specify the feedings.
        var feeding = {
          location : 'Location',
        };

        // create a marker with cluster enabled
        var  marker = new sap.viz.geo.dataviz.Marker({
             cluster :{
                 enabled: true
             }
        });

        // create a layer
        var layer = new sap.viz.geo.dataviz.Layer({
          viz : marker,
          data : ds,
          feeding : feeding
        });
        var delJS=['main_cluster.js'];
        var delCss=['style.css'];
        var delElementById=['setting','code-content','toggle','code'];
        toggleViewExtension("index_cluster.html","main_cluster.js",textArea,delJS,delCss,delElementById);

        // add layer
        map.addLayer(layer, true);

    })
    

});
