$(function(){
    //set template paths
    sap.viz.api.env.Resource.path('sap.viz.api.env.Template.loadPaths', 
      ['../../../resources/libs/sap.viz/resources/chart/templates', 
      '../../../resources/libs/sap.viz/resources/geo/templates/?_viz_template_with_css=true'])

    //set map resource path
    sap.viz.api.env.Resource.path("sap.viz.map.Resources",
     "../../../resources/libs/sap.viz/resources/geo");

    //Apply template
    sap.viz.api.env.Template.set("standard_lumira",function(){
          // initialize a cvom base map
        var baseMapProvider = new sap.viz.geo.basemap.cvom.Provider();

        // create chart
        var map = new sap.viz.geo.Map($('#chart').get(0), {baseMap : baseMapProvider});
        var textArea = document.getElementById('code-content');
        // prepare data
        var data = {
          "metadata" : {
            "fields" : [{
              "id" : "Location",
              "name" : "Location",
              "semanticType" : "Dimension",
              "dataType" : "String"
            }, {
              "id" : "Value",
              "name" : "Value",
              "semanticType" : "Measure"
            }]
          },
          "data" : [
             ['F. Yugoslav Repub. of Macedonia', Math.random() * 100],
             ['Isle of Man', Math.random() * 100],
             ['Afghanistan', Math.random() * 100],
             ['South Africa', Math.random() * 100],
             ['Ireland', Math.random() * 100],
             ['Netherlands', Math.random() * 100],
             ['Albania', Math.random() * 100],
             ['Germany', Math.random() * 100],
             ['Algeria', Math.random() * 100],
             ['US Virgin Islands', Math.random() * 100],
             ['United States', Math.random() * 100],
             ['Belarus', Math.random() * 100],
             ['Belgium', Math.random() * 100],
             ['Bosnia and Herzegovina', Math.random() * 100],
             ['Bulgaria', Math.random() * 100],
             ['Croatia', Math.random() * 100],
             ['Denmark', Math.random() * 100],
             ['Estonia', Math.random() * 100],
             ['Switzerland', Math.random() * 100],
             ['Finland', Math.random() * 100],
             ['Greece', Math.random() * 100],
             ['Italy', Math.random() * 100],
             ['Norway', Math.random() * 100],
             ['Latvia', Math.random() * 100],
             ['Lithuania', Math.random() * 100],
             ['Moldova', Math.random() * 100],
             ['Austria', Math.random() * 100],
             ['Poland', Math.random() * 100],
             ['Portugal', Math.random() * 100],
             ['Romania', Math.random() * 100],
             ['Russia', Math.random() * 100],
             ['Spain', Math.random() * 100],
             ['Serbia', Math.random() * 100],
             ['Slovenia', Math.random() * 100],
             ['Slovakia', Math.random() * 100],
             ['Sweden', Math.random() * 100],
             ['Turkey', Math.random() * 100],
             ['Hungary', Math.random() * 100],
             ['Iceland', Math.random() * 100],
             ['Ukraine', Math.random() * 100],
             ['Andorra', Math.random() * 100],
             ['Angola', Math.random() * 100],
             ['Saudi Arabia', Math.random() * 100],
             ['Argentina', Math.random() * 100],
             ['Armenia', Math.random() * 100],
             ['Australia', Math.random() * 100],
             ['Azerbaijan', Math.random() * 100],
             ['Bahamas, The', Math.random() * 100],
             ['Bahrain', Math.random() * 100],
             ['West Bank', Math.random() * 100],
             ['Bangladesh', Math.random() * 100],
             ['Barbados', Math.random() * 100],
             ['Belize', Math.random() * 100],
             ['Benin', Math.random() * 100],
             ['Bhutan', Math.random() * 100],
             ['Bolivia', Math.random() * 100],
             ['Botswana', Math.random() * 100],
             ['Brazil', Math.random() * 100],
             ['Brunei Darussalam', Math.random() * 100],
             ['Burkina Faso', Math.random() * 100],
             ['Burma (Myanmar)', Math.random() * 100],
             ['Burundi', Math.random() * 100],
             ['Cambodia', Math.random() * 100],
             ['Cameroon', Math.random() * 100],
             ['Canada', Math.random() * 100],
             ['Cape Verde', Math.random() * 100],
             ['Cayman Islands', Math.random() * 100],
             ['Central African Republic', Math.random() * 100],
             ['Chad', Math.random() * 100],
             ['Chile', Math.random() * 100],
             ['China', Math.random() * 100],
             ['Colombia', Math.random() * 100],
             ['Congo, Democratic Republic', Math.random() * 100],
             ['Congo, Republic of the', Math.random() * 100],
             ['Costa Rica', Math.random() * 100],
             ['Cote D Ivoire (Ivory Coast)', Math.random() * 100],
             ['Montenegro', Math.random() * 100],
             ['Czech Republic', Math.random() * 100],
             ['Cuba', Math.random() * 100],
             ['Cyprus un Neutral Zone', Math.random() * 100],
             ['Cyprus', Math.random() * 100],
             ['Djibouti', Math.random() * 100],
             ['Dominican Republic', Math.random() * 100],
             ['East Timor', Math.random() * 100],
             ['Ecuador', Math.random() * 100],
             ['Egypt', Math.random() * 100],
             ['El Salvador', Math.random() * 100],
             ['United Arab Emirates', Math.random() * 100],
             ['Equatorial Guinea', Math.random() * 100],
             ['Eritrea', Math.random() * 100],
             ['Ethiopia', Math.random() * 100],
             ['Falkland Islands (Islas Malvinas)', Math.random() * 100],
             ['France', Math.random() * 100],
             ['Fiji', Math.random() * 100],
             ['French-Guadeloupe', Math.random() * 100],
             ['French-Guiana', Math.random() * 100],
             ['French-Martinique', Math.random() * 100],
             ['French-Reunion', Math.random() * 100],
             ['Gabon', Math.random() * 100],
             ['Gambia', Math.random() * 100],
             ['Gaza Strip', Math.random() * 100],
             ['Georgia', Math.random() * 100],
             ['Ghana', Math.random() * 100],
             ['Jamaica', Math.random() * 100],
             ['Jordan', Math.random() * 100],
             ['Greenland', Math.random() * 100],
             ['Guatemala', Math.random() * 100],
             ['Guinea', Math.random() * 100],
             ['Guinea-Bissau', Math.random() * 100],
             ['Guyana', Math.random() * 100],
             ['Haiti', Math.random() * 100],
             ['Honduras', Math.random() * 100],
             ['India', Math.random() * 100],
             ['Iraq', Math.random() * 100],
             ['Iran', Math.random() * 100],
             ['Israel', Math.random() * 100],
             ['Japan', Math.random() * 100],
             ['Yemen', Math.random() * 100],
             ['Kazakhstan', Math.random() * 100],
             ['Qatar', Math.random() * 100],
             ['Kenya', Math.random() * 100],
             ['Kyrgyzstan', Math.random() * 100],
             ['Kuwait', Math.random() * 100],
             ['South Korea', Math.random() * 100],
             ['Laos', Math.random() * 100],
             ['Lebanon', Math.random() * 100],
             ['Lesotho', Math.random() * 100],
             ['Liberia', Math.random() * 100],
             ['Libya', Math.random() * 100],
             ['Liechtenstein', Math.random() * 100],
             ['Luxembourg', Math.random() * 100],
             ['Madagascar', Math.random() * 100],
             ['Malaysia', Math.random() * 100],
             ['Malawi', Math.random() * 100],
             ['Mali', Math.random() * 100],
             ['Malta', Math.random() * 100],
             ['Mauritania', Math.random() * 100],
             ['Mauritius', Math.random() * 100],
             ['Mayotte', Math.random() * 100],
             ['Mexico', Math.random() * 100],
             ['Mongolia', Math.random() * 100],
             ['Morocco', Math.random() * 100],
             ['Mozambique', Math.random() * 100],
             ['Namibia', Math.random() * 100],
             ['Nepal', Math.random() * 100],
             ['New Caledonia', Math.random() * 100],
             ['Nicaragua', Math.random() * 100],
             ['Niger', Math.random() * 100],
             ['Nigeria', Math.random() * 100],
             ['New Zealand', Math.random() * 100],
             ['Uzbekistan', Math.random() * 100],
             ['Oman', Math.random() * 100],
             ['Puerto Rico', Math.random() * 100],
             ['Pakistan', Math.random() * 100],
             ['Panama', Math.random() * 100],
             ['Papua New Guinea', Math.random() * 100],
             ['Paraguay', Math.random() * 100],
             ['Peru', Math.random() * 100],
             ['Philippines', Math.random() * 100],
             ['United Kingdom', Math.random() * 100],
             ['Venezuela', Math.random() * 100],
             ['Rwanda', Math.random() * 100],
             ['Saint Lucia', Math.random() * 100],
             ['Saint Pierre and Miquelon', Math.random() * 100],
             ['Senegal', Math.random() * 100],
             ['Sierra Leone', Math.random() * 100],
             ['Singapore', Math.random() * 100],
             ['Syria', Math.random() * 100],
             ['Sudan', Math.random() * 100],
             ['Solomon Islands', Math.random() * 100],
             ['Somalia', Math.random() * 100],
             ['South Korea', Math.random() * 100],
             ['Sri Lanka', Math.random() * 100],
             ['Suriname', Math.random() * 100],
             ['Svalbard', Math.random() * 100],
             ['Swaziland', Math.random() * 100],
             ['Taiwan', Math.random() * 100],
             ['Tajikistan', Math.random() * 100],
             ['Tanzania', Math.random() * 100],
             ['Thailand', Math.random() * 100],
             ['Togo', Math.random() * 100],
             ['Trinidad and Tobago', Math.random() * 100],
             ['Tunisia', Math.random() * 100],
             ['Turkmenistan', Math.random() * 100],
             ['Uganda', Math.random() * 100],
             ['Uruguay', Math.random() * 100],
             ['Vietnam', Math.random() * 100],
             ['Zambia', Math.random() * 100],
             ['Zimbabwe', Math.random() * 100],
             ['Indonesia', Math.random() * 100],
             ['Hong Kong-China', Math.random() * 100]
          ],
          "info" : [{
            "type" : "geo",
            "info" : [
                [{'featureId':'23796253,NAVTEQ'}],
                [{'featureId':'20486695,NAVTEQ'}],
                [{'featureId':'23528373,NAVTEQ'}],
                [{'featureId':'23402002,NAVTEQ'}],
                [{'featureId':'20403667,NAVTEQ'}],
                [{'featureId':'23055544,NAVTEQ'}],
                [{'featureId':'20678151,NAVTEQ'}],
                [{'featureId':'20147700,NAVTEQ'}],
                [{'featureId':'22927666,NAVTEQ'}],
                [{'featureId':'21486367,NAVTEQ'}],
                [{'featureId':'21000001,NAVTEQ'}],
                [{'featureId':'22832579,NAVTEQ'}],
                [{'featureId':'20128886,NAVTEQ'}],
                [{'featureId':'20676254,NAVTEQ'}],
                [{'featureId':'20656214,NAVTEQ'}],
                [{'featureId':'20633739,NAVTEQ'}],
                [{'featureId':'20298369,NAVTEQ'}],
                [{'featureId':'20633738,NAVTEQ'}],
                [{'featureId':'20138137,NAVTEQ'}],
                [{'featureId':'20241487,NAVTEQ'}],
                [{'featureId':'20448870,NAVTEQ'}],
                [{'featureId':'20110484,NAVTEQ'}],
                [{'featureId':'20418433,NAVTEQ'}],
                [{'featureId':'20633737,NAVTEQ'}],
                [{'featureId':'20633740,NAVTEQ'}],
                [{'featureId':'20678153,NAVTEQ'}],
                [{'featureId':'20128885,NAVTEQ'}],
                [{'featureId':'20624059,NAVTEQ'}],
                [{'featureId':'20317122,NAVTEQ'}],
                [{'featureId':'20656215,NAVTEQ'}],
                [{'featureId':'20485579,NAVTEQ'}],
                [{'featureId':'20215059,NAVTEQ'}],
                [{'featureId':'23832388,NAVTEQ'}],
                [{'featureId':'20633685,NAVTEQ'}],
                [{'featureId':'20428682,NAVTEQ'}],
                [{'featureId':'20298368,NAVTEQ'}],
                [{'featureId':'22709441,NAVTEQ'}],
                [{'featureId':'20613038,NAVTEQ'}],
                [{'featureId':'23517927,NAVTEQ'}],
                [{'featureId':'23674902,NAVTEQ'}],
                [{'featureId':'20300625,NAVTEQ'}],
                [{'featureId':'22927764,NAVTEQ'}],
                [{'featureId':'21375962,NAVTEQ'}],
                [{'featureId':'23294156,NAVTEQ'}],
                [{'featureId':'22928263,NAVTEQ'}],
                [{'featureId':'21482883,NAVTEQ'}],
                [{'featureId':'22928312,NAVTEQ'}],
                [{'featureId':'23382869,NAVTEQ'}],
                [{'featureId':'21420453,NAVTEQ'}],
                [{'featureId':'23919168,NAVTEQ'}],
                [{'featureId':'22928307,NAVTEQ'}],
                [{'featureId':'22928245,NAVTEQ'}],
                [{'featureId':'23671176,NAVTEQ'}],
                [{'featureId':'22927676,NAVTEQ'}],
                [{'featureId':'22928283,NAVTEQ'}],
                [{'featureId':'22928244,NAVTEQ'}],
                [{'featureId':'22832174,NAVTEQ'}],
                [{'featureId':'23028911,NAVTEQ'}],
                [{'featureId':'23287002,NAVTEQ'}],
                [{'featureId':'22927672,NAVTEQ'}],
                [{'featureId':'22928301,NAVTEQ'}],
                [{'featureId':'22927763,NAVTEQ'}],
                [{'featureId':'22928258,NAVTEQ'}],
                [{'featureId':'22927743,NAVTEQ'}],
                [{'featureId':'21041602,NAVTEQ'}],
                [{'featureId':'22927664,NAVTEQ'}],
                [{'featureId':'23382874,NAVTEQ'}],
                [{'featureId':'22927744,NAVTEQ'}],
                [{'featureId':'22927730,NAVTEQ'}],
                [{'featureId':'23488354,NAVTEQ'}],
                [{'featureId':'22928332,NAVTEQ'}],
                [{'featureId':'23656250,NAVTEQ'}],
                [{'featureId':'22927698,NAVTEQ'}],
                [{'featureId':'22927626,NAVTEQ'}],
                [{'featureId':'23671186,NAVTEQ'}],
                [{'featureId':'22927695,NAVTEQ'}],
                [{'featureId':'22903211,NAVTEQ'}],
                [{'featureId':'20427915,NAVTEQ'}],
                [{'featureId':'23671187,NAVTEQ'}],
                [{'featureId':'23740915,NAVTEQ'}],
                [{'featureId':'23502650,NAVTEQ'}],
                [{'featureId':'22927701,NAVTEQ'}],
                [{'featureId':'23671189,NAVTEQ'}],
                [{'featureId':'23714314,NAVTEQ'}],
                [{'featureId':'22928218,NAVTEQ'}],
                [{'featureId':'23713588,NAVTEQ'}],
                [{'featureId':'23671179,NAVTEQ'}],
                [{'featureId':'21397206,NAVTEQ'}],
                [{'featureId':'22927739,NAVTEQ'}],
                [{'featureId':'22927686,NAVTEQ'}],
                [{'featureId':'22927671,NAVTEQ'}],
                [{'featureId':'22928216,NAVTEQ'}],
                [{'featureId':'20000001,NAVTEQ'}],
                [{'featureId':'23582190,NAVTEQ'}],
                [{'featureId':'23410565,NAVTEQ'}],
                [{'featureId':'23382586,NAVTEQ'}],
                [{'featureId':'23410558,NAVTEQ'}],
                [{'featureId':'23382345,NAVTEQ'}],
                [{'featureId':'22927654,NAVTEQ'}],
                [{'featureId':'22927673,NAVTEQ'}],
                [{'featureId':'23919167,NAVTEQ'}],
                [{'featureId':'22928376,NAVTEQ'}],
                [{'featureId':'22927614,NAVTEQ'}],
                [{'featureId':'23671185,NAVTEQ'}],
                [{'featureId':'23059529,NAVTEQ'}],
                [{'featureId':'23667698,NAVTEQ'}],
                [{'featureId':'23671211,NAVTEQ'}],
                [{'featureId':'22927738,NAVTEQ'}],
                [{'featureId':'22927635,NAVTEQ'}],
                [{'featureId':'23726115,NAVTEQ'}],
                [{'featureId':'23671210,NAVTEQ'}],
                [{'featureId':'23671207,NAVTEQ'}],
                [{'featureId':'22806254,NAVTEQ'}],
                [{'featureId':'23528375,NAVTEQ'}],
                [{'featureId':'23528374,NAVTEQ'}],
                [{'featureId':'23528376,NAVTEQ'}],
                [{'featureId':'22928357,NAVTEQ'}],
                [{'featureId':'22927640,NAVTEQ'}],
                [{'featureId':'22928289,NAVTEQ'}],
                [{'featureId':'21417285,NAVTEQ'}],
                [{'featureId':'23704449,NAVTEQ'}],
                [{'featureId':'22928266,NAVTEQ'}],
                [{'featureId':'21405268,NAVTEQ'}],
                [{'featureId':'22928269,NAVTEQ'}],
                [{'featureId':'22928299,NAVTEQ'}],
                [{'featureId':'23514592,NAVTEQ'}],
                [{'featureId':'22832175,NAVTEQ'}],
                [{'featureId':'22927690,NAVTEQ'}],
                [{'featureId':'22927678,NAVTEQ'}],
                [{'featureId':'20209045,NAVTEQ'}],
                [{'featureId':'20128887,NAVTEQ'}],
                [{'featureId':'22927675,NAVTEQ'}],
                [{'featureId':'23289295,NAVTEQ'}],
                [{'featureId':'22927682,NAVTEQ'}],
                [{'featureId':'22927721,NAVTEQ'}],
                [{'featureId':'23667688,NAVTEQ'}],
                [{'featureId':'22927776,NAVTEQ'}],
                [{'featureId':'22927634,NAVTEQ'}],
                [{'featureId':'22927765,NAVTEQ'}],
                [{'featureId':'22000493,NAVTEQ'}],
                [{'featureId':'22928264,NAVTEQ'}],
                [{'featureId':'23362024,NAVTEQ'}],
                [{'featureId':'23495768,NAVTEQ'}],
                [{'featureId':'22832176,NAVTEQ'}],
                [{'featureId':'22928273,NAVTEQ'}],
                [{'featureId':'23582176,NAVTEQ'}],
                [{'featureId':'23671198,NAVTEQ'}],
                [{'featureId':'23727855,NAVTEQ'}],
                [{'featureId':'23702349,NAVTEQ'}],
                [{'featureId':'23060936,NAVTEQ'}],
                [{'featureId':'22928336,NAVTEQ'}],
                [{'featureId':'21425362,NAVTEQ'}],
                [{'featureId':'21177795,NAVTEQ'}],
                [{'featureId':'22928320,NAVTEQ'}],
                [{'featureId':'23671200,NAVTEQ'}],
                [{'featureId':'23502663,NAVTEQ'}],
                [{'featureId':'22928238,NAVTEQ'}],
                [{'featureId':'23695790,NAVTEQ'}],
                [{'featureId':'23869478,NAVTEQ'}],
                [{'featureId':'UK,NAVTEQ'}],
                [{'featureId':'23355239,NAVTEQ'}],
                [{'featureId':'22927772,NAVTEQ'}],
                [{'featureId':'22928212,NAVTEQ'}],
                [{'featureId':'23715814,NAVTEQ'}],
                [{'featureId':'22927668,NAVTEQ'}],
                [{'featureId':'22927745,NAVTEQ'}],
                [{'featureId':'21160468,NAVTEQ'}],
                [{'featureId':'23528377,NAVTEQ'}],
                [{'featureId':'22927717,NAVTEQ'}],
                [{'featureId':'23502661,NAVTEQ'}],
                [{'featureId':'22927612,NAVTEQ'}],
                [{'featureId':'22928340,NAVTEQ'}],
                [{'featureId':'22928342,NAVTEQ'}],
                [{'featureId':'22928232,NAVTEQ'}],
                [{'featureId':'23667693,NAVTEQ'}],
                [{'featureId':'22832177,NAVTEQ'}],
                [{'featureId':'23525046,NAVTEQ'}],
                [{'featureId':'22928314,NAVTEQ'}],
                [{'featureId':'22927692,NAVTEQ'}],
                [{'featureId':'22888206,NAVTEQ'}],
                [{'featureId':'22927620,NAVTEQ'}],
                [{'featureId':'22928196,NAVTEQ'}],
                [{'featureId':'22927704,NAVTEQ'}],
                [{'featureId':'22928362,NAVTEQ'}],
                [{'featureId':'23835855,NAVTEQ'}],
                [{'featureId':'22928233,NAVTEQ'}],
                [{'featureId':'22928359,NAVTEQ'}],
                [{'featureId':'22927728,NAVTEQ'}],
                [{'featureId':'23930431,NAVTEQ'}],
                [{'featureId':'23457314,NAVTEQ'}],
                [{'featureId':'21162124,NAVTEQ'}],
            ]
          }]
        };

        var ds = new sap.viz.api.data.FlatTableDataset(data);

        // specify the feedings.
        var feeding = {
          location : 'Location',
          color : 'Value'
        };

        // create a choropleth
        var choropleth = new sap.viz.geo.dataviz.Choropleth();

        // create a layer
        var layer = new sap.viz.geo.dataviz.Layer({
          viz : choropleth,
          data : ds,
          feeding : feeding
        });
        var delJS=['main_mbc.js'];
        var delCss=['style.css'];
        var delElementById=['setting','code-content','toggle','code'];
        toggleViewExtension("index_mbc.html","main_mbc.js",textArea,delJS,delCss,delElementById);

        // add layer
        map.addLayer(layer, true);

    })
    

});
