$(function(){
    //set template paths
    sap.viz.api.env.Resource.path('sap.viz.api.env.Template.loadPaths', 
      ['../../../resources/libs/sap.viz/resources/chart/templates', 
      '../../../resources/libs/sap.viz/resources/geo/templates/?_viz_template_with_css=true'])

    //set map resource path
    sap.viz.api.env.Resource.path("sap.viz.map.Resources", 
      "../../../resources/libs/sap.viz/resources/geo");

    //Apply template
    sap.viz.api.env.Template.set("highcontrast",function(){
          // initialize a cvom base map
        var baseMapProvider = new sap.viz.geo.basemap.cvom.Provider();

        // create chart
        var map = new sap.viz.geo.Map($('#chart').get(0), {baseMap : baseMapProvider});
 
        var popluar = ["hot", "warm", "cold"];
        var textArea = document.getElementById('code-content');
        // prepare data
        // prepare data
        var data = {
          "metadata" : {
            "fields" : [{
              "id" : "Location",
              "name" : "Location",
              "semanticType" : "Dimension",
              "dataType" : "String"
            }, {
              "id" : "Value",
              "name" : "Country Temperature Category",
              "semanticType" : "Dimension"
            }]
          },
          "data" : [
              ['ANC. Rép. Yougoslave de Macédoine ', popluar[Math.floor(Math.random() * 3)]],
              ['Adam Adası ', popluar[Math.floor(Math.random() * 3)]],
              ['Afghanistan ', popluar[Math.floor(Math.random() * 3)]],
              ['Afrique du Sud ', popluar[Math.floor(Math.random() * 3)]],
              ['Airija ', popluar[Math.floor(Math.random() * 3)]],
              ['Alankomaat ', popluar[Math.floor(Math.random() * 3)]],
              ['Albaania ', popluar[Math.floor(Math.random() * 3)]],
              ['Alemanha ', popluar[Math.floor(Math.random() * 3)]],
              ['Algeria ', popluar[Math.floor(Math.random() * 3)]],
              ['Amerikaanse Maagdeneilanden ', popluar[Math.floor(Math.random() * 3)]],
              ['Amerikas Förenta Stater ', popluar[Math.floor(Math.random() * 3)]],
              ['An Bhealarúis ', popluar[Math.floor(Math.random() * 3)]],
              ['An Bheilg ', popluar[Math.floor(Math.random() * 3)]],
              ['An Bhoisnia Heirseagaivéin ', popluar[Math.floor(Math.random() * 3)]],
              ['An Bhulgáir ', popluar[Math.floor(Math.random() * 3)]],
              ['An Chróit ', popluar[Math.floor(Math.random() * 3)]],
              ['An Danmhairg ', popluar[Math.floor(Math.random() * 3)]],
              ['An Eastóin ', popluar[Math.floor(Math.random() * 3)]],
              ['An Eilvéis ', popluar[Math.floor(Math.random() * 3)]],
              ['An Fhionlainn ', popluar[Math.floor(Math.random() * 3)]],
              ['An Ghréig ', popluar[Math.floor(Math.random() * 3)]],
              ['An Iodáil ', popluar[Math.floor(Math.random() * 3)]],
              ['An Iorua ', popluar[Math.floor(Math.random() * 3)]],
              ['An Laitvia ', popluar[Math.floor(Math.random() * 3)]],
              ['An Liotuáin ', popluar[Math.floor(Math.random() * 3)]],
              ['An Mholdóiv ', popluar[Math.floor(Math.random() * 3)]],
              ['An Ostair ', popluar[Math.floor(Math.random() * 3)]],
              ['An Pholainn ', popluar[Math.floor(Math.random() * 3)]],
              ['An Phortaingéil ', popluar[Math.floor(Math.random() * 3)]],
              ['An Rómáin ', popluar[Math.floor(Math.random() * 3)]],
              ['An Rúis ', popluar[Math.floor(Math.random() * 3)]],
              ['An Spáinn ', popluar[Math.floor(Math.random() * 3)]],
              ['An Tseirbia ', popluar[Math.floor(Math.random() * 3)]],
              ['An Tslóivéin ', popluar[Math.floor(Math.random() * 3)]],
              ['An Tslóvaic ', popluar[Math.floor(Math.random() * 3)]],
              ['An Tsualainn ', popluar[Math.floor(Math.random() * 3)]],
              ['An Tuirc ', popluar[Math.floor(Math.random() * 3)]],
              ['An Ungáir ', popluar[Math.floor(Math.random() * 3)]],
              ['An Íoslainn ', popluar[Math.floor(Math.random() * 3)]],
              ['An Úcráin ', popluar[Math.floor(Math.random() * 3)]],
              ['Andora ', popluar[Math.floor(Math.random() * 3)]],
              ['Angola ', popluar[Math.floor(Math.random() * 3)]],
              ['Arabia Saudita ', popluar[Math.floor(Math.random() * 3)]],
              ['Argentina ', popluar[Math.floor(Math.random() * 3)]],
              ['Armenia ', popluar[Math.floor(Math.random() * 3)]],
              ['Australia ', popluar[Math.floor(Math.random() * 3)]],
              ['Azerbaijan ', popluar[Math.floor(Math.random() * 3)]],
              ['Bahamas, The ', popluar[Math.floor(Math.random() * 3)]],
              ['Bahrain ', popluar[Math.floor(Math.random() * 3)]],
              ['Banco Oeste ', popluar[Math.floor(Math.random() * 3)]],
              ['Bangladesh ', popluar[Math.floor(Math.random() * 3)]],
              ['Barbade ', popluar[Math.floor(Math.random() * 3)]],
              ['Belize ', popluar[Math.floor(Math.random() * 3)]],
              ['Benin ', popluar[Math.floor(Math.random() * 3)]],
              ['Bhutan ', popluar[Math.floor(Math.random() * 3)]],
              ['Bolivia ', popluar[Math.floor(Math.random() * 3)]],
              ['Botsuana ', popluar[Math.floor(Math.random() * 3)]],
              ['Brasil ', popluar[Math.floor(Math.random() * 3)]],
              ['Brunei Darussalam ', popluar[Math.floor(Math.random() * 3)]],
              ['Burkina Faso ', popluar[Math.floor(Math.random() * 3)]],
              ['Burma (Myanmar) ', popluar[Math.floor(Math.random() * 3)]],
              ['Burundi ', popluar[Math.floor(Math.random() * 3)]],
              ['Cambodia ', popluar[Math.floor(Math.random() * 3)]],
              ['Cameroon ', popluar[Math.floor(Math.random() * 3)]],
              ['Canada ', popluar[Math.floor(Math.random() * 3)]],
              ['Cape Verde ', popluar[Math.floor(Math.random() * 3)]],
              ['Cayman Islands ', popluar[Math.floor(Math.random() * 3)]],
              ['Central African Republic ', popluar[Math.floor(Math.random() * 3)]],
              ['Chad ', popluar[Math.floor(Math.random() * 3)]],
              ['Chile ', popluar[Math.floor(Math.random() * 3)]],
              ['China ', popluar[Math.floor(Math.random() * 3)]],
              ['Colombia ', popluar[Math.floor(Math.random() * 3)]],
              ['Congo, Democratic Republic ', popluar[Math.floor(Math.random() * 3)]],
              ['Congo, Republic of the ', popluar[Math.floor(Math.random() * 3)]],
              ['Costa Rica ', popluar[Math.floor(Math.random() * 3)]],
              ['Cote D Ivoire (Ivory Coast) ', popluar[Math.floor(Math.random() * 3)]],
              ['Crna Gora ', popluar[Math.floor(Math.random() * 3)]],
              ['Csehország ', popluar[Math.floor(Math.random() * 3)]],
              ['Cuba ', popluar[Math.floor(Math.random() * 3)]],
              ['Cyprus un Neutral Zone ', popluar[Math.floor(Math.random() * 3)]],
              ['Cyprus ', popluar[Math.floor(Math.random() * 3)]],
              ['Djibouti ', popluar[Math.floor(Math.random() * 3)]],
              ['Dominicaanse Republiek ', popluar[Math.floor(Math.random() * 3)]],
              ['East Timor ', popluar[Math.floor(Math.random() * 3)]],
              ['Ecuador ', popluar[Math.floor(Math.random() * 3)]],
              ['Egipto ', popluar[Math.floor(Math.random() * 3)]],
              ['El Salvador ', popluar[Math.floor(Math.random() * 3)]],
              ['Emirati Arabi Uniti ', popluar[Math.floor(Math.random() * 3)]],
              ['Equatorial Guinea ', popluar[Math.floor(Math.random() * 3)]],
              ['Eritrea ', popluar[Math.floor(Math.random() * 3)]],
              ['Ethiopia ', popluar[Math.floor(Math.random() * 3)]],
              ['Falkland Islands (Islas Malvinas) ', popluar[Math.floor(Math.random() * 3)]],
              ['Ffrainc ', popluar[Math.floor(Math.random() * 3)]],
              ['Fiji ', popluar[Math.floor(Math.random() * 3)]],
              ['Frans-Guadeloupe ', popluar[Math.floor(Math.random() * 3)]],
              ['Frans-Guyana ', popluar[Math.floor(Math.random() * 3)]],
              ['Frans-Martinique ', popluar[Math.floor(Math.random() * 3)]],
              ['Frans-Reunion ', popluar[Math.floor(Math.random() * 3)]],
              ['Gabon ', popluar[Math.floor(Math.random() * 3)]],
              ['Gambia ', popluar[Math.floor(Math.random() * 3)]],
              ['Gaza Strip ', popluar[Math.floor(Math.random() * 3)]],
              ['Georgia ', popluar[Math.floor(Math.random() * 3)]],
              ['Ghana ', popluar[Math.floor(Math.random() * 3)]],
              ['Giamaica ', popluar[Math.floor(Math.random() * 3)]],
              ['Giordania ', popluar[Math.floor(Math.random() * 3)]],
              ['Greenland ', popluar[Math.floor(Math.random() * 3)]],
              ['Guatemala ', popluar[Math.floor(Math.random() * 3)]],
              ['Guinea ', popluar[Math.floor(Math.random() * 3)]],
              ['Guinea-Bissau ', popluar[Math.floor(Math.random() * 3)]],
              ['Guyana ', popluar[Math.floor(Math.random() * 3)]],
              ['Haiti ', popluar[Math.floor(Math.random() * 3)]],
              ['Honduras ', popluar[Math.floor(Math.random() * 3)]],
              ['India ', popluar[Math.floor(Math.random() * 3)]],
              ['Irak ', popluar[Math.floor(Math.random() * 3)]],
              ['Iran ', popluar[Math.floor(Math.random() * 3)]],
              ['Israel ', popluar[Math.floor(Math.random() * 3)]],
              ['Japan ', popluar[Math.floor(Math.random() * 3)]],
              ['Jemen ', popluar[Math.floor(Math.random() * 3)]],
              ['Kasachstan ', popluar[Math.floor(Math.random() * 3)]],
              ['Katar ', popluar[Math.floor(Math.random() * 3)]],
              ['Kenia ', popluar[Math.floor(Math.random() * 3)]],
              ['Kirghizistan ', popluar[Math.floor(Math.random() * 3)]],
              ['Koeweit ', popluar[Math.floor(Math.random() * 3)]],
              ['North Korea', popluar[Math.floor(Math.random() * 3)]],
              ['Laos ', popluar[Math.floor(Math.random() * 3)]],
              ['Lebanon ', popluar[Math.floor(Math.random() * 3)]],
              ['Lesotho ', popluar[Math.floor(Math.random() * 3)]],
              ['Liberia ', popluar[Math.floor(Math.random() * 3)]],
              ['Libia ', popluar[Math.floor(Math.random() * 3)]],
              ['Lichtensztajn ', popluar[Math.floor(Math.random() * 3)]],
              ['Liuksemburgas ', popluar[Math.floor(Math.random() * 3)]],
              ['Madagascar ', popluar[Math.floor(Math.random() * 3)]],
              ['Malaisie ', popluar[Math.floor(Math.random() * 3)]],
              ['Malawi ', popluar[Math.floor(Math.random() * 3)]],
              ['Mali ', popluar[Math.floor(Math.random() * 3)]],
              ['Malta ', popluar[Math.floor(Math.random() * 3)]],
              ['Mauritania ', popluar[Math.floor(Math.random() * 3)]],
              ['Mauritius ', popluar[Math.floor(Math.random() * 3)]],
              ['Mayotte ', popluar[Math.floor(Math.random() * 3)]],
              ['Messico ', popluar[Math.floor(Math.random() * 3)]],
              ['Mongolei ', popluar[Math.floor(Math.random() * 3)]],
              ['Morocco ', popluar[Math.floor(Math.random() * 3)]],
              ['Mosambik ', popluar[Math.floor(Math.random() * 3)]],
              ['Namibia ', popluar[Math.floor(Math.random() * 3)]],
              ['Nepal ', popluar[Math.floor(Math.random() * 3)]],
              ['New Caledonia ', popluar[Math.floor(Math.random() * 3)]],
              ['Nicaragua ', popluar[Math.floor(Math.random() * 3)]],
              ['Niger ', popluar[Math.floor(Math.random() * 3)]],
              ['Nigeria ', popluar[Math.floor(Math.random() * 3)]],
              ['Nouvelle-Zélande ', popluar[Math.floor(Math.random() * 3)]],
              ['Oezbekistan ', popluar[Math.floor(Math.random() * 3)]],
              ['Oman ', popluar[Math.floor(Math.random() * 3)]],
              ['PR ', popluar[Math.floor(Math.random() * 3)]],
              ['Pakistan ', popluar[Math.floor(Math.random() * 3)]],
              ['Panama ', popluar[Math.floor(Math.random() * 3)]],
              ['Papua New Guinea ', popluar[Math.floor(Math.random() * 3)]],
              ['Paraguay ', popluar[Math.floor(Math.random() * 3)]],
              ['Peru ', popluar[Math.floor(Math.random() * 3)]],
              ['Philippines ', popluar[Math.floor(Math.random() * 3)]],
              ['Renju Unit ', popluar[Math.floor(Math.random() * 3)]],
              ['República Bolivariana de Venezuela ', popluar[Math.floor(Math.random() * 3)]],
              ['Rwanda ', popluar[Math.floor(Math.random() * 3)]],
              ['Saint Lucia ', popluar[Math.floor(Math.random() * 3)]],
              ['Saint Pierre and Miquelon ', popluar[Math.floor(Math.random() * 3)]],
              ['Senegal ', popluar[Math.floor(Math.random() * 3)]],
              ['Sierra Leone ', popluar[Math.floor(Math.random() * 3)]],
              ['Singapore ', popluar[Math.floor(Math.random() * 3)]],
              ['Siria ', popluar[Math.floor(Math.random() * 3)]],
              ['Soedan ', popluar[Math.floor(Math.random() * 3)]],
              ['Solomon Islands ', popluar[Math.floor(Math.random() * 3)]],
              ['Somalia ', popluar[Math.floor(Math.random() * 3)]],
              ['South Korea ', popluar[Math.floor(Math.random() * 3)]],
              ['Sri Lanka ', popluar[Math.floor(Math.random() * 3)]],
              ['Suriname ', popluar[Math.floor(Math.random() * 3)]],
              ['Svalbard ', popluar[Math.floor(Math.random() * 3)]],
              ['Swasiland ', popluar[Math.floor(Math.random() * 3)]],
              ['Taiwan ', popluar[Math.floor(Math.random() * 3)]],
              ['Tajikistan ', popluar[Math.floor(Math.random() * 3)]],
              ['Tanzania ', popluar[Math.floor(Math.random() * 3)]],
              ['Thailand ', popluar[Math.floor(Math.random() * 3)]],
              ['Togo ', popluar[Math.floor(Math.random() * 3)]],
              ['Trinidad and Tobago ', popluar[Math.floor(Math.random() * 3)]],
              ['Tunisia ', popluar[Math.floor(Math.random() * 3)]],
              ['Turkmenistan ', popluar[Math.floor(Math.random() * 3)]],
              ['Uganda ', popluar[Math.floor(Math.random() * 3)]],
              ['Uruguay ', popluar[Math.floor(Math.random() * 3)]],
              ['Vietnam ', popluar[Math.floor(Math.random() * 3)]],
              ['Zambia ', popluar[Math.floor(Math.random() * 3)]],
              ['Zimbabue ', popluar[Math.floor(Math.random() * 3)]],
              ['Indonesia', popluar[Math.floor(Math.random() * 3)]],
              ['香港-中國 ', popluar[Math.floor(Math.random() * 3)]],
          ],
          "info" : [{
            "type" : "geo",
            "info" : [
                [{'featureId':'23796253,NAVTEQ'}],
                [{'featureId':'20486695,NAVTEQ'}],
                [{'featureId':'23528373,NAVTEQ'}],
                [{'featureId':'23402002,NAVTEQ'}],
                [{'featureId':'20403667,NAVTEQ'}],
                [{'featureId':'23055544,NAVTEQ'}],
                [{'featureId':'20678151,NAVTEQ'}],
                [{'featureId':'20147700,NAVTEQ'}],
                [{'featureId':'22927666,NAVTEQ'}],
                [{'featureId':'21486367,NAVTEQ'}],
                [{'featureId':'21000001,NAVTEQ'}],
                [{'featureId':'22832579,NAVTEQ'}],
                [{'featureId':'20128886,NAVTEQ'}],
                [{'featureId':'20676254,NAVTEQ'}],
                [{'featureId':'20656214,NAVTEQ'}],
                [{'featureId':'20633739,NAVTEQ'}],
                [{'featureId':'20298369,NAVTEQ'}],
                [{'featureId':'20633738,NAVTEQ'}],
                [{'featureId':'20138137,NAVTEQ'}],
                [{'featureId':'20241487,NAVTEQ'}],
                [{'featureId':'20448870,NAVTEQ'}],
                [{'featureId':'20110484,NAVTEQ'}],
                [{'featureId':'20418433,NAVTEQ'}],
                [{'featureId':'20633737,NAVTEQ'}],
                [{'featureId':'20633740,NAVTEQ'}],
                [{'featureId':'20678153,NAVTEQ'}],
                [{'featureId':'20128885,NAVTEQ'}],
                [{'featureId':'20624059,NAVTEQ'}],
                [{'featureId':'20317122,NAVTEQ'}],
                [{'featureId':'20656215,NAVTEQ'}],
                [{'featureId':'20485579,NAVTEQ'}],
                [{'featureId':'20215059,NAVTEQ'}],
                [{'featureId':'23832388,NAVTEQ'}],
                [{'featureId':'20633685,NAVTEQ'}],
                [{'featureId':'20428682,NAVTEQ'}],
                [{'featureId':'20298368,NAVTEQ'}],
                [{'featureId':'22709441,NAVTEQ'}],
                [{'featureId':'20613038,NAVTEQ'}],
                [{'featureId':'23517927,NAVTEQ'}],
                [{'featureId':'23674902,NAVTEQ'}],
                [{'featureId':'20300625,NAVTEQ'}],
                [{'featureId':'22927764,NAVTEQ'}],
                [{'featureId':'21375962,NAVTEQ'}],
                [{'featureId':'23294156,NAVTEQ'}],
                [{'featureId':'22928263,NAVTEQ'}],
                [{'featureId':'21482883,NAVTEQ'}],
                [{'featureId':'22928312,NAVTEQ'}],
                [{'featureId':'23382869,NAVTEQ'}],
                [{'featureId':'21420453,NAVTEQ'}],
                [{'featureId':'23919168,NAVTEQ'}],
                [{'featureId':'22928307,NAVTEQ'}],
                [{'featureId':'22928245,NAVTEQ'}],
                [{'featureId':'23671176,NAVTEQ'}],
                [{'featureId':'22927676,NAVTEQ'}],
                [{'featureId':'22928283,NAVTEQ'}],
                [{'featureId':'22928244,NAVTEQ'}],
                [{'featureId':'22832174,NAVTEQ'}],
                [{'featureId':'23028911,NAVTEQ'}],
                [{'featureId':'23287002,NAVTEQ'}],
                [{'featureId':'22927672,NAVTEQ'}],
                [{'featureId':'22928301,NAVTEQ'}],
                [{'featureId':'22927763,NAVTEQ'}],
                [{'featureId':'22928258,NAVTEQ'}],
                [{'featureId':'22927743,NAVTEQ'}],
                [{'featureId':'21041602,NAVTEQ'}],
                [{'featureId':'22927664,NAVTEQ'}],
                [{'featureId':'23382874,NAVTEQ'}],
                [{'featureId':'22927744,NAVTEQ'}],
                [{'featureId':'22927730,NAVTEQ'}],
                [{'featureId':'23488354,NAVTEQ'}],
                [{'featureId':'22928332,NAVTEQ'}],
                [{'featureId':'23656250,NAVTEQ'}],
                [{'featureId':'22927698,NAVTEQ'}],
                [{'featureId':'22927626,NAVTEQ'}],
                [{'featureId':'23671186,NAVTEQ'}],
                [{'featureId':'22927695,NAVTEQ'}],
                [{'featureId':'22903211,NAVTEQ'}],
                [{'featureId':'20427915,NAVTEQ'}],
                [{'featureId':'23671187,NAVTEQ'}],
                [{'featureId':'23740915,NAVTEQ'}],
                [{'featureId':'23502650,NAVTEQ'}],
                [{'featureId':'22927701,NAVTEQ'}],
                [{'featureId':'23671189,NAVTEQ'}],
                [{'featureId':'23714314,NAVTEQ'}],
                [{'featureId':'22928218,NAVTEQ'}],
                [{'featureId':'23713588,NAVTEQ'}],
                [{'featureId':'23671179,NAVTEQ'}],
                [{'featureId':'21397206,NAVTEQ'}],
                [{'featureId':'22927739,NAVTEQ'}],
                [{'featureId':'22927686,NAVTEQ'}],
                [{'featureId':'22927671,NAVTEQ'}],
                [{'featureId':'22928216,NAVTEQ'}],
                [{'featureId':'20000001,NAVTEQ'}],
                [{'featureId':'23582190,NAVTEQ'}],
                [{'featureId':'23410565,NAVTEQ'}],
                [{'featureId':'23382586,NAVTEQ'}],
                [{'featureId':'23410558,NAVTEQ'}],
                [{'featureId':'23382345,NAVTEQ'}],
                [{'featureId':'22927654,NAVTEQ'}],
                [{'featureId':'22927673,NAVTEQ'}],
                [{'featureId':'23919167,NAVTEQ'}],
                [{'featureId':'22928376,NAVTEQ'}],
                [{'featureId':'22927614,NAVTEQ'}],
                [{'featureId':'23671185,NAVTEQ'}],
                [{'featureId':'23059529,NAVTEQ'}],
                [{'featureId':'23667698,NAVTEQ'}],
                [{'featureId':'23671211,NAVTEQ'}],
                [{'featureId':'22927738,NAVTEQ'}],
                [{'featureId':'22927635,NAVTEQ'}],
                [{'featureId':'23726115,NAVTEQ'}],
                [{'featureId':'23671210,NAVTEQ'}],
                [{'featureId':'23671207,NAVTEQ'}],
                [{'featureId':'22806254,NAVTEQ'}],
                [{'featureId':'23528375,NAVTEQ'}],
                [{'featureId':'23528374,NAVTEQ'}],
                [{'featureId':'23528376,NAVTEQ'}],
                [{'featureId':'22928357,NAVTEQ'}],
                [{'featureId':'22927640,NAVTEQ'}],
                [{'featureId':'22928289,NAVTEQ'}],
                [{'featureId':'21417285,NAVTEQ'}],
                [{'featureId':'23704449,NAVTEQ'}],
                [{'featureId':'22928266,NAVTEQ'}],
                [{'featureId':'21405268,NAVTEQ'}],
                [{'featureId':'22928269,NAVTEQ'}],
                [{'featureId':'22928299,NAVTEQ'}],
                [{'featureId':'23514592,NAVTEQ'}],
                [{'featureId':'22832175,NAVTEQ'}],
                [{'featureId':'22927690,NAVTEQ'}],
                [{'featureId':'22927678,NAVTEQ'}],
                [{'featureId':'20209045,NAVTEQ'}],
                [{'featureId':'20128887,NAVTEQ'}],
                [{'featureId':'22927675,NAVTEQ'}],
                [{'featureId':'23289295,NAVTEQ'}],
                [{'featureId':'22927682,NAVTEQ'}],
                [{'featureId':'22927721,NAVTEQ'}],
                [{'featureId':'23667688,NAVTEQ'}],
                [{'featureId':'22927776,NAVTEQ'}],
                [{'featureId':'22927634,NAVTEQ'}],
                [{'featureId':'22927765,NAVTEQ'}],
                [{'featureId':'22000493,NAVTEQ'}],
                [{'featureId':'22928264,NAVTEQ'}],
                [{'featureId':'23362024,NAVTEQ'}],
                [{'featureId':'23495768,NAVTEQ'}],
                [{'featureId':'22832176,NAVTEQ'}],
                [{'featureId':'22928273,NAVTEQ'}],
                [{'featureId':'23582176,NAVTEQ'}],
                [{'featureId':'23671198,NAVTEQ'}],
                [{'featureId':'23727855,NAVTEQ'}],
                [{'featureId':'23702349,NAVTEQ'}],
                [{'featureId':'23060936,NAVTEQ'}],
                [{'featureId':'22928336,NAVTEQ'}],
                [{'featureId':'21425362,NAVTEQ'}],
                [{'featureId':'21177795,NAVTEQ'}],
                [{'featureId':'22928320,NAVTEQ'}],
                [{'featureId':'23671200,NAVTEQ'}],
                [{'featureId':'23502663,NAVTEQ'}],
                [{'featureId':'22928238,NAVTEQ'}],
                [{'featureId':'23695790,NAVTEQ'}],
                [{'featureId':'23869478,NAVTEQ'}],
                [{'featureId':'UK,NAVTEQ'}],
                [{'featureId':'23355239,NAVTEQ'}],
                [{'featureId':'22927772,NAVTEQ'}],
                [{'featureId':'22928212,NAVTEQ'}],
                [{'featureId':'23715814,NAVTEQ'}],
                [{'featureId':'22927668,NAVTEQ'}],
                [{'featureId':'22927745,NAVTEQ'}],
                [{'featureId':'21160468,NAVTEQ'}],
                [{'featureId':'23528377,NAVTEQ'}],
                [{'featureId':'22927717,NAVTEQ'}],
                [{'featureId':'23502661,NAVTEQ'}],
                [{'featureId':'22927612,NAVTEQ'}],
                [{'featureId':'22928340,NAVTEQ'}],
                [{'featureId':'22928342,NAVTEQ'}],
                [{'featureId':'22928232,NAVTEQ'}],
                [{'featureId':'23667693,NAVTEQ'}],
                [{'featureId':'22832177,NAVTEQ'}],
                [{'featureId':'23525046,NAVTEQ'}],
                [{'featureId':'22928314,NAVTEQ'}],
                [{'featureId':'22927692,NAVTEQ'}],
                [{'featureId':'22888206,NAVTEQ'}],
                [{'featureId':'22927620,NAVTEQ'}],
                [{'featureId':'22928196,NAVTEQ'}],
                [{'featureId':'22927704,NAVTEQ'}],
                [{'featureId':'22928362,NAVTEQ'}],
                [{'featureId':'23835855,NAVTEQ'}],
                [{'featureId':'22928233,NAVTEQ'}],
                [{'featureId':'22928359,NAVTEQ'}],
                [{'featureId':'22927728,NAVTEQ'}],
                [{'featureId':'23930431,NAVTEQ'}],
                [{'featureId':'23457314,NAVTEQ'}],
                [{'featureId':'21162124,NAVTEQ'}],
            ]
          }]
        };

        var ds = new sap.viz.api.data.FlatTableDataset(data);

        // specify the feedings.
        var feeding = {
          location : 'Location',
          color : 'Value'
        };

        // create a bubble
        var bubble = new sap.viz.geo.dataviz.Bubble({
            colorPalette: ["red", "orange", "blue"]
        });
        var delJS=['main_measure.js'];
        var delCss=['style.css'];
        var delElementById=['setting','code-content','toggle','code'];
        toggleViewExtension("index_measure.html","main_measure.js",textArea,delJS,delCss,delElementById);
        // create a layer
        var layer = new sap.viz.geo.dataviz.Layer({
          viz : bubble,
          data : ds,
          feeding : feeding
        });
        
        // add layer
        map.addLayer(layer, true);

    })
    

});
